//! Parity checks against the cross-certificate currently installed in the trust stores.
//!
//! The Rust implementation must produce a certificate that is a drop-in replacement for
//! the one generated by the previous shell implementation. Anything that changes the
//! Subject DN encoding or the Subject Key Identifier breaks every chain already in use, so
//! those are compared byte-for-byte against the live artifacts in the workspace.
//!
//! These tests are skipped when the workspace files are absent, so the suite still passes
//! on a clean checkout.

use std::path::{Path, PathBuf};

use rucerts::config::Config;
use rucerts::x509::{cross_sign, load_cert, load_key, permitted_dns, ski_hex};
use openssl::x509::X509;

fn workspace() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

/// Loads the live root, its key, the original CA root and the installed cross-certificate.
fn live_artifacts() -> Option<(X509, openssl::pkey::PKey<openssl::pkey::Private>, X509, X509)> {
    let w = workspace();
    let root = w.join("myroot.pem");
    let key = w.join("myroot.key");
    let original = w.join("roots/russian_trusted_root_ca.cer");
    let installed = w.join("constrained/russian_trusted_root_ca.pem");

    if ![&root, &key, &original, &installed].iter().all(|p| p.exists()) {
        return None;
    }
    Some((
        load_cert(&root).expect("root"),
        load_key(&key).expect("root key"),
        load_cert(&original).expect("original"),
        load_cert(&installed).expect("installed cross-certificate"),
    ))
}

/// DER-encoded object identifier `2.5.29.30`, `nameConstraints`.
const OID_NAME_CONSTRAINTS: &[u8] = &[0x06, 0x03, 0x55, 0x1D, 0x1E];
/// DER-encoded object identifier `2.5.29.19`, `basicConstraints`.
const OID_BASIC_CONSTRAINTS: &[u8] = &[0x06, 0x03, 0x55, 0x1D, 0x13];
/// DER-encoded object identifier `2.5.29.15`, `keyUsage`.
const OID_KEY_USAGE: &[u8] = &[0x06, 0x03, 0x55, 0x1D, 0x0F];

/// Returns the DER contents of a certificate's extension, located by its OID bytes.
///
/// The openssl crate exposes no generic extension accessor, so the certificate's own
/// encoding is scanned. Extensions appear as `SEQUENCE { OID, BOOLEAN OPTIONAL, OCTET
/// STRING }`; the OID is located and the following OCTET STRING returned.
fn extension_der(cert: &X509, oid: &[u8]) -> Option<Vec<u8>> {
    let der = cert.to_der().ok()?;
    let mut idx = 0;
    while idx + oid.len() <= der.len() {
        if &der[idx..idx + oid.len()] == oid {
            let mut cursor = idx + oid.len();
            // Skip the optional `critical` BOOLEAN (tag 0x01, length 1, value).
            if der.get(cursor) == Some(&0x01) {
                cursor += 3;
            }
            if der.get(cursor) == Some(&0x04) {
                let (len, header) = der_len(&der[cursor + 1..])?;
                let start = cursor + 1 + header;
                return der.get(start..start + len).map(<[u8]>::to_vec);
            }
        }
        idx += 1;
    }
    None
}

/// Reads a DER length, returning the value and how many bytes the length itself occupied.
fn der_len(bytes: &[u8]) -> Option<(usize, usize)> {
    let first = *bytes.first()?;
    if first & 0x80 == 0 {
        return Some((first as usize, 1));
    }
    let count = (first & 0x7F) as usize;
    let mut value = 0_usize;
    for i in 0..count {
        value = (value << 8) | *bytes.get(1 + i)? as usize;
    }
    Some((value, 1 + count))
}

#[test]
fn subject_dn_is_byte_identical_to_the_installed_certificate() {
    let Some((root, key, original, installed)) = live_artifacts() else {
        eprintln!("workspace artifacts absent, skipping");
        return;
    };
    let cfg = Config::load(&workspace()).expect("config");

    let fresh = cross_sign(
        &root,
        &key,
        &original,
        &cfg.constraints,
        cfg.signing.cross_days,
        cfg.signing.path_len,
    )
    .expect("cross-sign");

    let fresh_dn = fresh.subject_name().to_der().expect("fresh DN");
    let installed_dn = installed.subject_name().to_der().expect("installed DN");
    let original_dn = original.subject_name().to_der().expect("original DN");

    assert_eq!(
        fresh_dn, installed_dn,
        "Subject DN differs from the installed certificate; every chain would break"
    );
    assert_eq!(
        fresh_dn, original_dn,
        "Subject DN differs from the original root; sub-CA issuer matching would fail"
    );
}

#[test]
fn subject_key_identifier_is_preserved() {
    let Some((root, key, original, installed)) = live_artifacts() else {
        eprintln!("workspace artifacts absent, skipping");
        return;
    };
    let cfg = Config::load(&workspace()).expect("config");

    let fresh = cross_sign(
        &root,
        &key,
        &original,
        &cfg.constraints,
        cfg.signing.cross_days,
        cfg.signing.path_len,
    )
    .expect("cross-sign");

    assert_eq!(ski_hex(&fresh), ski_hex(&original), "SKI must match original");
    assert_eq!(
        ski_hex(&fresh),
        ski_hex(&installed),
        "SKI must match the installed certificate"
    );
}

#[test]
fn name_constraints_der_matches_the_installed_certificate() {
    let Some((root, key, original, installed)) = live_artifacts() else {
        eprintln!("workspace artifacts absent, skipping");
        return;
    };
    let cfg = Config::load(&workspace()).expect("config");

    let fresh = cross_sign(
        &root,
        &key,
        &original,
        &cfg.constraints,
        cfg.signing.cross_days,
        cfg.signing.path_len,
    )
    .expect("cross-sign");

    let fresh_nc = extension_der(&fresh, OID_NAME_CONSTRAINTS).expect("fresh constraints");
    let installed_nc =
        extension_der(&installed, OID_NAME_CONSTRAINTS).expect("installed constraints");
    assert_eq!(
        fresh_nc, installed_nc,
        "nameConstraints encoding differs from the installed certificate"
    );
}

#[test]
fn basic_constraints_and_key_usage_match() {
    let Some((root, key, original, installed)) = live_artifacts() else {
        eprintln!("workspace artifacts absent, skipping");
        return;
    };
    let cfg = Config::load(&workspace()).expect("config");

    let fresh = cross_sign(
        &root,
        &key,
        &original,
        &cfg.constraints,
        cfg.signing.cross_days,
        cfg.signing.path_len,
    )
    .expect("cross-sign");

    for (label, oid) in [
        ("basicConstraints", OID_BASIC_CONSTRAINTS),
        ("keyUsage", OID_KEY_USAGE),
    ] {
        assert_eq!(
            extension_der(&fresh, oid),
            extension_der(&installed, oid),
            "{label} differs from the installed certificate"
        );
    }
}

#[test]
fn permitted_names_read_back_match_configuration() {
    let Some((root, key, original, _)) = live_artifacts() else {
        eprintln!("workspace artifacts absent, skipping");
        return;
    };
    let cfg = Config::load(&workspace()).expect("config");

    let fresh = cross_sign(
        &root,
        &key,
        &original,
        &cfg.constraints,
        cfg.signing.cross_days,
        cfg.signing.path_len,
    )
    .expect("cross-sign");

    assert_eq!(
        permitted_dns(&fresh).expect("read back"),
        cfg.constraints.permitted_dns
    );
}
